# Generated by Django 4.2.13 on 2024-08-08 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boundary',
            fields=[
                ('BID', models.CharField(max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message="PID must be in the format '01' followed by 6 digits.", regex='^05[0-9]{9}$')])),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'boundarys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('SID', models.CharField(max_length=12, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message="PID must be in the format '01' followed by 6 digits.", regex='^06[0-9]{10}$')])),
                ('Ename', models.CharField(max_length=255)),
                ('form', models.CharField(max_length=255)),
                ('MName', models.CharField(max_length=255)),
                ('category', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'boundarys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('EQID', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('unit', models.CharField(max_length=10)),
                ('coefficient', models.FloatField(blank=True, null=True)),
                ('purchase_date', models.DateField()),
                ('disposal_date', models.DateField()),
                ('age', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'equipments',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('MID', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('unit', models.CharField(max_length=10)),
                ('coefficient', models.FloatField(blank=True, null=True)),
                ('purchase_date', models.DateField()),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'materials',
            },
        ),
    ]
