# Generated by Django 4.2.13 on 2024-08-11 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ESG', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='source',
            table='sources',
        ),
    ]
