# Generated by Django 4.2.15 on 2024-09-01 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ESG', '0002_alter_source_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='Boundary',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
