# Generated by Django 4.2.14 on 2024-08-18 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Boundary",
            fields=[
                (
                    "BID",
                    models.CharField(max_length=11, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "boundary",
            },
        ),
        migrations.CreateModel(
            name="Emission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
            ],
            options={
                "db_table": "emission",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "EID",
                    models.CharField(max_length=12, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("gender", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=11)),
                ("nation", models.CharField(max_length=255)),
                ("status", models.IntegerField(default=1)),
            ],
            options={
                "db_table": "employees",
            },
        ),
        migrations.CreateModel(
            name="Gas",
            fields=[
                (
                    "GID",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("gwp", models.FloatField()),
            ],
            options={
                "db_table": "gas",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "PID",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("pname", models.CharField(max_length=255)),
                ("flow", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "projects",
            },
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("runtime", models.FloatField(blank=True, null=True)),
                ("amount", models.FloatField(blank=True, null=True)),
                ("unit", models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                "db_table": "records",
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "SRID",
                    models.CharField(max_length=14, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("amount", models.IntegerField()),
                ("unit", models.CharField(max_length=10)),
                ("purchase_date", models.DateField()),
                ("disposal_date", models.DateField()),
                ("age", models.IntegerField()),
                ("factor", models.FloatField(blank=True, null=True)),
                ("form", models.CharField(blank=True, max_length=10, null=True)),
                ("category", models.CharField(blank=True, max_length=10, null=True)),
                ("status", models.IntegerField(default=1)),
            ],
            options={
                "db_table": "source",
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "SID",
                    models.CharField(max_length=12, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=11)),
                ("nation", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "suppliers",
            },
        ),
        migrations.CreateModel(
            name="WorksOn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(max_length=255)),
                (
                    "EID",
                    models.ForeignKey(
                        db_column="EID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pm.employee",
                    ),
                ),
                (
                    "PID",
                    models.ForeignKey(
                        db_column="PID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pm.project",
                    ),
                ),
            ],
            options={
                "db_table": "works_on",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=255)),
                ("access", models.CharField(max_length=255)),
                (
                    "UID",
                    models.OneToOneField(
                        db_column="UID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pm.employee",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="Usage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                ("unit", models.CharField(max_length=45)),
                (
                    "PID",
                    models.ForeignKey(
                        db_column="PID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pm.project",
                    ),
                ),
                (
                    "SRID",
                    models.ForeignKey(
                        db_column="SRID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pm.source",
                    ),
                ),
            ],
            options={
                "db_table": "usage",
            },
        ),
        migrations.CreateModel(
            name="Supply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "SID",
                    models.ForeignKey(
                        db_column="SID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pm.supplier",
                    ),
                ),
                (
                    "SRID",
                    models.ForeignKey(
                        db_column="SRID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pm.source",
                    ),
                ),
            ],
            options={
                "db_table": "supply",
            },
        ),
        migrations.AddConstraint(
            model_name="supplier",
            constraint=models.CheckConstraint(
                check=models.Q(("SID__regex", "^05[0-9]{10}$")), name="check_sid_format"
            ),
        ),
        migrations.AddConstraint(
            model_name="supplier",
            constraint=models.CheckConstraint(
                check=models.Q(("phone__regex", "^[0-9]+$")), name="check_sphone_format"
            ),
        ),
        migrations.AddConstraint(
            model_name="source",
            constraint=models.CheckConstraint(
                check=models.Q(("SRID__regex", "^03[0-9]{12}$")),
                name="check_srid_format",
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="PID",
            field=models.ForeignKey(
                db_column="PID",
                on_delete=django.db.models.deletion.CASCADE,
                to="pm.project",
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="SRID",
            field=models.ForeignKey(
                db_column="SRID",
                on_delete=django.db.models.deletion.CASCADE,
                to="pm.source",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="BID",
            field=models.ForeignKey(
                db_column="BID",
                on_delete=django.db.models.deletion.CASCADE,
                to="pm.boundary",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="PMID",
            field=models.ForeignKey(
                db_column="PMID",
                on_delete=django.db.models.deletion.CASCADE,
                to="pm.user",
                to_field="UID",
            ),
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.CheckConstraint(
                check=models.Q(("EID__regex", "^02[0-9]{10}$")), name="check_eid_format"
            ),
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "email__regex",
                        "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$",
                    )
                ),
                name="check_email_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.CheckConstraint(
                check=models.Q(("phone__regex", "^[0-9]+$")), name="check_phone_format"
            ),
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.CheckConstraint(
                check=models.Q(("gender__in", [1, 2])), name="employees_chk_1"
            ),
        ),
        migrations.AddField(
            model_name="emission",
            name="GID",
            field=models.ForeignKey(
                db_column="GID",
                on_delete=django.db.models.deletion.CASCADE,
                to="pm.gas",
            ),
        ),
        migrations.AddField(
            model_name="emission",
            name="SRID",
            field=models.ForeignKey(
                db_column="SRID",
                on_delete=django.db.models.deletion.CASCADE,
                to="pm.source",
            ),
        ),
        migrations.AddConstraint(
            model_name="boundary",
            constraint=models.CheckConstraint(
                check=models.Q(("BID__regex", "^04[0-9]{9}$")), name="check_bid_format"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workson",
            unique_together={("EID", "PID")},
        ),
        migrations.AlterUniqueTogether(
            name="usage",
            unique_together={("PID", "SRID")},
        ),
        migrations.AlterUniqueTogether(
            name="supply",
            unique_together={("SID", "SRID")},
        ),
        migrations.AlterUniqueTogether(
            name="record",
            unique_together={("PID", "SRID", "date")},
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                check=models.Q(("PID__regex", "^01[0-9]{6}$")), name="check_pid_format"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="emission",
            unique_together={("SRID", "GID")},
        ),
    ]
