# Generated by Django 4.2.15 on 2024-09-01 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='PMID',
            field=models.ForeignKey(db_column='PMID', on_delete=django.db.models.deletion.CASCADE, to='pm.employee'),
        ),
        migrations.AlterModelTable(
            name='record',
            table='record',
        ),
    ]
